<a href="https://colab.research.google.com/github/ammaralda/intro-pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
import numpy as np

# Example

In [3]:
tensor_2d = torch.rand(2, 3)
tensor_2d

tensor([[0.0447, 0.2096, 0.3031],
        [0.7096, 0.4684, 0.5566]])

In [4]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
# create a 2x2 numpy array
arr = np.array([[1, 2], [3, 4]])
arr


array([[1, 2],
       [3, 4]])

In [10]:
#create tensor from numpy
my_tensor = torch.tensor(arr)
my_tensor

tensor([[1, 2],
        [3, 4]])